"""Public Institute status. Catalog + sandbox evidence. Never LIVE_PIN_OK."""

from __future__ import annotations

from typing import Any

from ainav.catalog import catalog_engineering, honest_missing, load_catalog, sku
from ainav.microsoft.agent_tools import public_review as agent_tools_review
from ainav.microsoft.dns import catalog_edge

COMPLEMENT_HONESTY = {
    "entra.id": "Seat object ids. Not an IdP replacement. Copilot is not the admit plane.",
    "azure.keyvault": "Connection secret hold on the host. Not a live pin.",
    "azure.monitor": "Mothership health. LAW is not Sentinel. Not a live pin.",
    "sharepoint.kit": "Kit evidence store. Not a seat. Graph is not called from this page.",
    "defender.xdr": "E7 security sink. SecurityIncident.Read.All is not granted. Not the admit plane.",
    "entra.pim": "Eligible seats. A PIM activation is not dual admit.",
    "sentinel.siem": "DecisionRecord export sink. The mothership LAW is not a Sentinel workspace.",
    "azure.policy": "Host policy. West Europe is blocked. Cannot weaken Job C.",
}


def _sku_band(sku_id: str) -> dict[str, Any]:
    item = sku(sku_id)
    price = item["price_usd"]
    return {
        "id": sku_id,
        "name": item["name"],
        "kind": item["kind"],
        "min": price["min"],
        "max": price["max"],
        "term": item["term"],
    }


def _complements(cat: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {
            "id": item["id"],
            "product": item["product"],
            "role": item["role"],
            "binds": list(item.get("binds") or []),
            "wired": False,
            "live": False,
            "mode": "sandbox",
            "note": COMPLEMENT_HONESTY[item["id"]],
        }
        for item in cat["connections"]["complements"]
    ]


def _fabric(cat: dict[str, Any], evidence: dict[str, Any], site: dict[str, Any]) -> dict[str, Any]:
    return {
        "live": False,
        "product": cat["entity"]["product"],
        "not_the_product": cat["microsoft_stack"]["not_the_product"],
        "e7_not_the_product": list(cat["microsoft_stack"].get("e7_not_the_product") or []),
        "path": [
            {
                "id": "azure.host",
                "lane": "host",
                "product": "Microsoft Azure",
                "status": "hosted_sandbox",
                "note": f"{site.get('azure_site')} on {site.get('azure_location')}. Custom domain not bound.",
            },
            {
                "id": "m365.e7",
                "lane": "identity",
                "product": "Microsoft 365 E7 / Microsoft Entra ID",
                "status": "connected_sandbox",
                "note": "Seat object ids. Copilot is not a seat. PIM is not dual admit.",
            },
            {
                "id": "admit",
                "lane": "admit",
                "product": cat["entity"]["product"],
                "status": "running_code",
                "note": "Two distinct humans. One action hash. Then the write.",
            },
            {
                "id": "bc.premium",
                "lane": "sor",
                "product": "Dynamics 365 Business Central Premium",
                "status": "sandbox_journal",
                "note": (
                    f"{evidence['environment']} · {evidence['bc_company']} · "
                    f"{evidence['action_class']}. Production blocked."
                ),
            },
            {
                "id": "sales.enterprise",
                "lane": "sor",
                "product": "Dynamics 365 Sales Enterprise",
                "status": "licensed_not_wired",
                "note": "License exists. No Dataverse instance. Twin only until G14.",
            },
            {
                "id": "teams.enterprise",
                "lane": "notify",
                "product": "Microsoft Teams Enterprise",
                "status": "licensed_not_wired",
                "note": "Effect notify. A chat is not a seat.",
            },
            {
                "id": "teams.premium",
                "lane": "notify",
                "product": "Microsoft Teams Premium",
                "status": "licensed_not_wired",
                "note": "Protected notify. A meeting is not a seat.",
            },
        ],
    }


def _opportunity() -> dict[str, Any]:
    prove = _sku_band("L1")
    keep = _sku_band("P-ADM")
    deepen = _sku_band("U-DUAL")
    return {
        "prove": prove["id"],
        "keep": keep["id"],
        "deepen": deepen["id"],
        "recognized_revenue": None,
        "named_customers": [],
        "signed_l1": 0,
        "attached": {"L1": 0, "P-ADM": 0, "U-DUAL": 0},
        "list": {"L1": prove, "P-ADM": keep, "U-DUAL": deepen},
        "year_one_list_if_all_three": {
            "min": prove["min"] + keep["min"] + deepen["min"],
            "max": prove["max"] + keep["max"] + deepen["max"],
            "note": (
                "Catalog list if one controller buys L1, then attaches P-ADM, "
                "then pays for U-DUAL. Not recognized revenue."
            ),
        },
        "note": "Pipeline math uses catalog list prices. It is not recognized revenue.",
    }


def public_status() -> dict[str, Any]:
    cat = load_catalog()
    evidence = dict(cat["sandbox_evidence"])
    site = cat["programs"]["website"]
    tools = agent_tools_review()
    return {
        "kind": "ainav.institute.status.v1",
        "entity": cat["entity"]["legal"],
        "institute": cat["entity"]["institute"],
        "product": cat["entity"]["product"],
        "job": cat["entity"]["job"],
        "release": cat["entity"]["release"],
        "live": False,
        "live_pin_ok": False,
        "production": False,
        "wrote_sor": False,
        "signed_l1": False,
        "custom_domain_claimed": False,
        "launch_ready": False,
        "azure_url": site.get("azure_url"),
        "website": {
            "twin_host": site.get("twin_host"),
            "twin_review": bool(site.get("twin_review")),
            "review_path": site.get("review_path"),
            "public_edge": site.get("public_edge"),
            "authorized_release": False,
            "launch_ready": False,
            "pages_is_host": False,
            "azure_url": site.get("azure_url"),
            "managed": bool(site.get("managed")),
            "first_class": bool(site.get("first_class")),
            "dynamic": False,
            "cms": False,
            "demo_path": site.get("demo_path") or "#twin",
            "demo_is_sku": False,
            "path_href": site.get("path_href") or "#path",
            "client_twin_is_sku": False,
            "close_bench": bool(site.get("close_bench")),
            "close_is_sku": False,
            "operating_company": bool(site.get("operating_company")),
            "firm_href": site.get("firm_href") or "#firm",
            "firm_is_sku": False,
            "firm_is_crm": False,
            "operating_day": bool(site.get("operating_day")),
            "operating_day_is_sku": False,
            "launch_gate": bool(site.get("launch_gate")),
            "launch_is_ready": False,
            "microsoft_run": bool(site.get("microsoft_run")),
            "microsoft_run_is_sku": False,
            "microsoft_is_the_product": False,
            "microsoft_day_map": bool(site.get("microsoft_day_map")),
            "microsoft_day_map_is_sku": False,
            "microsoft_roster": bool(site.get("microsoft_roster")),
            "microsoft_roster_is_sku": False,
            "brand": bool(site.get("brand")),
            "brand_is_sku": False,
            "brand_href": site.get("brand_href") or "#brand",
            "client_universe": bool(site.get("client_universe")),
            "universe_is_sku": False,
            "universe_href": site.get("universe_href") or "#universe",
            "universe_operable": bool(site.get("universe_operable")),
            "universe_wells_live": False,
            "universe_sit_down": bool(site.get("universe_sit_down")),
            "universe_day_live": False,
            "industry_drawer": bool(site.get("industry_drawer")),
            "industry_is_sku": False,
            "industry_href": site.get("industry_href") or "#industry",
            "industry_drawer_live": False,
            "industry_certified": False,
            "industry_rooms": bool(site.get("industry_rooms")),
            "industry_crypto": False,
            "industry_seventeen_a4": False,
            "industry_operable": bool(site.get("industry_operable")),
            "industry_fully_operable": bool(site.get("industry_fully_operable")),
            "industry_complete": bool(site.get("industry_complete")),
            "industry_control": bool(site.get("industry_control")),
            "industry_honest": bool(site.get("industry_honest")),
            "industry_control_live": False,
            "industry_rooms_live": False,
            "industry_wells_live": False,
            "microsoft_agents": bool(site.get("microsoft_agents")),
            "microsoft_agents_honest": bool(site.get("microsoft_agents_honest")),
            "microsoft_agents_live": False,
            "microsoft_census": False,
            "agent_365_is_product": False,
            "honest_access": bool(site.get("honest_access")),
            "honest_access_live": False,
            "additional_access_needed": False,
            "grok_is_product": False,
            "grok_is_seat": False,
            "honest_operators": bool(site.get("honest_operators")),
            "honest_operators_live": False,
            "operator_swap": False,
            "grok_is_recorded": False,
            "bot_is_operator": False,
            "honest_build": bool(site.get("honest_build")),
            "honest_build_live": False,
            "full_access_needed": False,
            "twin_is_launch": False,
            "packs_are_skus": False,
            "honest_readiness": bool(site.get("honest_readiness")),
            "honest_readiness_live": False,
            "gold_is_launch": False,
            "twin_is_launch_day": False,
            "sim_is_production": False,
            "update_is_live_pin": False,
            "launch_day_certified": False,
            "honest_industry": bool(site.get("honest_industry")),
            "honest_industry_live": False,
            "industry_certified_launch": False,
            "honest_whole": bool(site.get("honest_whole")),
            "honest_whole_live": False,
            "whole_is_launch": False,
            "ten_is_launch": False,
            "stitch_is_sku": False,
            "honest_power_pages": bool(site.get("honest_power_pages")),
            "honest_power_pages_live": False,
            "power_pages_is_host": False,
            "power_pages_is_sku": False,
            "power_pages_is_cms": False,
            "power_pages_closes_dataverse": False,
            "honest_copilot_studio": bool(site.get("honest_copilot_studio")),
            "honest_copilot_studio_live": False,
            "copilot_studio_is_job_c": False,
            "copilot_studio_is_sku": False,
            "copilot_studio_is_admit": False,
            "copilot_studio_is_complement": False,
            "copilot_studio_is_seat": False,
            "honest_connect": bool(site.get("honest_connect")),
            "honest_connect_live": False,
            "connected_is_live": False,
            "licensed_is_wired": False,
            "available_is_seat": False,
            "graph_read_is_live_pin": False,
            "cursor_app_is_seat": False,
            "honest_operate": bool(site.get("honest_operate")),
            "honest_operate_live": False,
            "close_gaps_is_this_plane": False,
            "outlook_is_click": False,
            "grok_login_is_this_plane": False,
            "operate_sim_is_production": False,
            "polish_ten_is_launch": False,
            "honest_path": bool(site.get("honest_path")),
            "honest_path_live": False,
            "industry_is_named_client": False,
            "shared_sandbox_is_production": False,
            "hours_is_sku": False,
            "rollback_is_live_pin": False,
            "redeploy_is_launch": False,
            "honest_production": bool(site.get("honest_production")),
            "honest_production_live": False,
            "production_sim_is_production": False,
            "fix_all_is_this_plane": False,
            "elements_are_live": False,
            "better_is_launch": False,
            "rehearsal_is_live_pin": False,
            "honest_remainder": bool(site.get("honest_remainder")),
            "honest_remainder_live": False,
            "remainder_is_launch": False,
            "leftover_copy_is_live_pin": False,
            "owner_hrefs_are_clicks": False,
            "gold_995_is_production": False,
            "deep_remainder_is_seated": False,
            "honest_ten": bool(site.get("honest_ten")),
            "honest_ten_live": False,
            "quality_ten_is_launch": False,
            "gold_999_is_live_pin": False,
            "compete_is_named_client": False,
            "service_green_is_production": False,
            "quality_is_seated": False,
            "honest_protect": bool(site.get("honest_protect")),
            "honest_protect_live": False,
            "protect_as_patent": False,
            "protect_as_uncopyable": False,
            "client_license_as_assignment": False,
            "kit_pass_as_source": False,
            "g12_as_closed": False,
            "honest_hold": bool(site.get("honest_hold")),
            "honest_hold_live": False,
            "vault_as_live_pin": False,
            "names_as_wired": False,
            "secret_in_catalog": False,
            "sentinel_as_admit": False,
            "hold_as_seated": False,
            "honest_close": bool(site.get("honest_close")),
            "honest_close_live": False,
            "close_as_launch": False,
            "booking_as_revenue": False,
            "twin_as_assigned": False,
            "custom_db_as_sku": False,
            "list_as_collection": False,
            "honest_join": bool(site.get("honest_join")),
            "honest_join_live": False,
            "join_as_launch": False,
            "stitch_as_live_pin": False,
            "licensed_as_wired_firm": False,
            "manage_ops_as_closed": False,
            "certify_as_running": False,
        },
        "bc": {
            "connection": "bc.premium",
            "product": "Dynamics 365 Business Central Premium",
            "environment": evidence["environment"],
            "operating_company": evidence["bc_company"],
            "operating_company_id": evidence["bc_company_id"],
            "wedge": evidence["action_class"],
            "sandbox_document": evidence["bc_document"],
            "amount": evidence["amount"],
            "date": evidence["date"],
            "live_pin_ok": False,
            "note": evidence["note"],
        },
        "sales": {
            "connection": "sales.enterprise",
            "product": "Dynamics 365 Sales Enterprise",
            "licensed": True,
            "wired": False,
            "instances": 0,
            "note": "License exists. No Dataverse instance. Twin only until G14.",
        },
        "identity": {
            "connection": "m365.e7",
            "product": "Microsoft 365 E7 / Microsoft Entra ID",
            "note": "Seat object ids. Not an IdP replacement. Copilot is not the admit plane.",
        },
        "notify": {
            "connections": ["teams.enterprise", "teams.premium"],
            "wired": False,
            "note": "Licensed. A chat is not a seat.",
        },
        "host": {
            "connection": "azure.host",
            "location": "eastus / eastus2",
            "institute_site": site.get("azure_site"),
        },
        "fabric": _fabric(cat, evidence, site),
        "e7_cloudflare": catalog_edge(),
        "engineering": catalog_engineering(),
        "complements": _complements(cat),
        "agent_tools": {
            "admin_url": tools["admin_url"],
            "product": tools["product"],
            "wired": False,
            "live": False,
            "is_admit_plane": False,
            "cloud_agent_can_approve": False,
            "leave_available": [item["id"] for item in tools["leave_available"]],
            "block_until_dual": [item["id"] for item in tools["block_until_dual"]],
        },
        "opportunity": _opportunity(),
        "honest_missing": honest_missing(),
        "open_gaps": list(cat["open_gaps"]),
        "success_equation": cat["success_equation"],
        "commercial_equation": cat["equations"]["commercial"],
        "lab_pin": cat["equations"]["lab_pin"],
        "invited_second_human": {
            "name": cat["organization"]["contacts"]["invited"]["name"],
            "recorded": bool(cat["organization"]["contacts"]["invited"].get("recorded")),
            "agreed": bool(cat["organization"]["contacts"]["invited"].get("agreed")),
            "email": cat["organization"]["contacts"]["invited"].get("email"),
            "entra_oid": cat["organization"]["contacts"]["invited"].get("entra_oid"),
            "seat_clicked": bool(cat["organization"]["contacts"]["invited"].get("seat_clicked")),
        },
    }
